[workspace]
members = [
    "packages/*", 
    "contracts/core/memory",
    "contracts/core/treasury",
    "contracts/dapps/external/*",
    "contracts/dapps/internal/vault",
    "contracts/core/treasury",


]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
