[workspace]
members = [
    "bundles/*",
]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

[workspace.package]
version = "0.2.0"
authors = ["CyberHoward <cyberhoward@protonmail.com>", "Riada <riada@abstract.money>", "Abstract Money <contact@abstract.money>"]
edition = "2021"
homepage = "https://abstract.money"
documentation = "https://docs.abstract.money/"
repository = "https://github.com/Abstract-OS/integration-bundles"
license = "GPL-3.0-or-later"
keywords = ["integration", "testing", "CosmWasm"]

[workspace.dependencies]
cosmwasm-std = { version = "1.1.9" }
cosmwasm-schema = { version = "1.1.9" }
cw-storage-plus = "1.0.1"
cw20-base = { version = "1.0.1" }
cw20 = { version = "1.0.1" }

cw-asset = { version = "3.0" }

cw-semver = { version = "1.0"}
boot-core = { version = "0.8.0" }
boot-cw-plus = { version = "0.8.0" }

abstract-macros = {version = "0.11" }
abstract-ica = { version = "0.11" }
abstract-os = { version = "0.12" }
abstract-sdk = { version = "0.12" }
abstract-app = { version = "0.12" }
abstract-api = { version = "0.12" }
abstract-ibc-host = { version = "0.11" }
abstract-boot = {version = "0.12" }

## Testing
cw-multi-test = { version = "0.16.2" }
anyhow = "1"
# rstest = "0.16.0"
# speculoos = "0.11.0"