name: check

on: [push, pull_request]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      changes_in_framework: ${{ steps.filter.outputs.framework == 'true' }}
      changes_in_adapters: ${{ steps.filter.outputs.adapters == 'true' }}
      changes_in_app_template: ${{ steps.filter.outputs.app_template == 'true' }}
      changes_in_integration_bundles: ${{ steps.filter.outputs.integration_bundles == 'true' }}
      changes_in_integrations: ${{ steps.filter.outputs.integrations == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          framework:
            - './framework/**.rs'
          adapters:
            - './adapters/**.rs'
          app_template:
            - './app-template/**.rs'
          integration_bundles:
            - './integration-bundles/**.rs'
          integrations:
            - './integrations/**.rs'

  just-check:
    needs: paths-filter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Setup | Just
      id: just
      uses: extractions/setup-just@v1
    - name: Run just check on framework
      if: needs.paths-filter.outputs.changes_in_framework
      run: just check-all framework
    - name: Run just check on adapters
      if: needs.paths-filter.outputs.changes_in_adapters
      run: just check-all adapters
    - name: Run just check on app_template
      if: needs.paths-filter.outputs.changes_in_app_template
      run: just check-all app_template
    - name: Run just check on integration_bundles
      if: needs.paths-filter.outputs.changes_in_integration_bundles
      run: just check-all integration_bundles
    - name: Run just check on integrations
      if: needs.paths-filter.outputs.changes_in_integrations
      run: (just check integrations/wyndex && just check integrations/astroport && just check integrations/osmosis)
