name: framework-test
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths: 
      - framework/**
  pull_request:
    paths: 
      - framework/**

env: 
  CODECOV_TOKEN: 7f09ca79-34d7-4a5a-b6fd-b3b477a7b2e9
  WORKSPACE_PATH: ./framework

jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: (cd $WORKSPACE_PATH && cargo generate-lockfile)
      # https://twitter.com/jonhoo/status/1571290371124260865
      - name: cargo test --locked
        run: (cd $WORKSPACE_PATH && cargo test --locked --all-features --all-targets)
  coverage:
    runs-on: ubuntu-latest
    name: ubuntu / stable / coverage
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: (cd $WORKSPACE_PATH && cargo generate-lockfile)
      - name: cargo llvm-cov
        run: (cd $WORKSPACE_PATH && cargo llvm-cov --locked --all-features --lcov --output-path lcov.info)
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
